name: news_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  get: 4.6.5
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
